[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
favorites = "FuaqGRQRdEpv1K57HjanFS2rAqQYb1aRUykfxrzmfYxQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
